README.md
src/Mixins/JoinRelationship.php
src/Mixins/RelationshipsExtraMethods.php
src/PowerJoinClause.php
tests/JoinRelationshipTest.php
tests/JoinRelationshipUsingAliasTest.php
tests/Models/Category.php
tests/Models/Group.php
tests/Models/Post.php
tests/database/factories/CategoryFactory.php
tests/database/factories/PostFactory.php
tests/database/migrations/2020_03_16_000000_create_tables.php

This PR implements the ability to use table aliases in the joins being made. It can be used in two ways.
By calling the `joinRelationshipUsingAlias` method.
```php
Post::joinRelationshipUsingAlias('category.parent')->get();
```
This generates the following query:
```sql
SELECT "posts".* FROM "posts"
INNER JOIN "categories" AS "40071de3fbcf4e9399e166813abb7718" ON "posts"."category_id" = "40071de3fbcf4e9399e166813abb7718"."id"
INNER JOIN "categories" AS "ccecda2ab44b29ec904f7bdea7e5aa2e" ON "40071de3fbcf4e9399e166813abb7718"."parent_id" = "ccecda2ab44b29ec904f7bdea7e5aa2e"."id"
```
You can also manually specify the table alias you want to use in the join callbacks.
```php
Post::joinRelationship('category.parent', [
'parent' => function ($join) {
$join->as('category_parent');
},
])->get(); …
```

Feature: Table aliases

---

CHANGELOG.md
src/PowerJoinClause.php
tests/JoinRelationshipTest.php

Fixed the ability to pass nested closures in join callbacks when using aliases

---

src/PowerJoins.php
tests/JoinRelationshipTest.php

This is related to issue #32 
Since the join cache was never cleared old spl_object_id()'s were being used at random during the script execution causing the query to not perform any joins.

Make sure join cache is cleared between queries

---

src/PowerJoinClause.php

Currently, using the scopes, you can't chain more scopes like so:
```php
User::joinRelationship('bookableResources', fn ($q) => $q->verified()->banned())
```
Using the code above, `banned()` fails because the return for `verified()` is `void`.

Add ability to chain scopes

---

src/PowerJoins.php
tests/JoinRelationshipUsingAliasTest.php

Hi,
Thanks for your awesome package. 
As stated in #74  if you provide a custom alias as a string it gets ignored and an autogenerated alias is used instead.
In this PR I have created a possible fix and added a test.
Cheers
fixes #74

added check to see if the used alias should be custom or user provided

---

.github/workflows/ci.yaml

Laravel 7 does not support PHP 8.1. I have excluded it from the tests. 
It still tests Laravel 8 and 9 in combination with PHP 8.1

Run CI tests also on PHP 8.1 

---

src/PowerJoins.php
tests/JoinRelationshipTest.php

This is an attempt at fixing Issue #90. I'm not 100% sure this is the cleanest way to do this but it's passing automated tests and I set up the following example locally and it seems like the SQL is correct.
```php
Route::get('/', function () {
$query = Post::query()->joinRelationship('author');
$query->joinRelationship('author.department');
$query->joinRelationship('author.department.organization');
return $query->dd();
});
```
```sql
SELECT
`posts`.*
FROM
`posts`
INNER JOIN `users` ON `posts`.`author_id` = `users`.`id`
INNER JOIN `departments` ON `users`.`department_id` = `departments`.`id`
INNER JOIN `organizations` ON `departments`.`organization_id` = `organizations`.`id`
```

Potential Fix: Using `joinRelationship` on the same base relationship(s)

---

README.md

**Before:**
>Let's imagine, you have a `Image` model that is a polymorphic relationship (`Post -> morphMany -> Image`). Besides the regular join, you would also need to apply the `where imageable_type = Image::class` condition, otherwise you could get messy results.
**After:**
>Let's imagine, you have a `Image` model that is a polymorphic relationship (`Post -> morphMany -> Image`). Besides the regular join, you would also need to apply the `where imageable_type = Post::class` condition, otherwise you could get messy results.

Fix class name in Joining polymorphic relationships section of Readme

---

src/PowerJoinClause.php

Hello,
Thank you for this package it's really nice to be able to reuse already defined relations like this.
While using your package i found out that it isn't possible to call QueryBuilder macros on JoinClause.
I like to be able to extend builders functionalities this way so i was wondering if you would consider allowing the call to be passed to the underlying builder.
Thanks for your time.

Allow Macro calls on JoinClause

---

src/Mixins/RelationshipsExtraMethods.php
tests/JoinRelationshipExtraConditionsTest.php
tests/Models/User.php
tests/database/factories/PostFactory.php
tests/database/migrations/2020_03_16_000000_create_tables.php

When a relationship has a nested condition that contains a `WHERE ... OR ...` statement, this condition was not encapsulated inside parenthesis, unlike the "actual" relationship.
```php
public function publishedOrReviewedPosts(): HasMany
{
return $this->hasMany(Post::class)->where(function($q){
$q->where('published', true);
$q->orWhere('reviewed', true);
});
}
```
Gave the following query after the relationship was joined : 
```php
$query = User::joinRelationship('publishedOrReviewedPosts')->toSql();
dd($query); // [...] inner join "posts" on "posts"."user_id" = "users"."id" and "published" = ? or "reviewed" = ? [...]
```
This was leading to unexpected results, since the correct behavior was to put `"published" = ? or "reviewed" = ?` inside parenthesis.
This PR fixes this issue.
I also …

Encapsultate nested conditions inside a where statement

---

src/PowerJoinClause.php
src/PowerJoins.php
tests/JoinRelationshipUsingAliasTest.php

This changes for one part, fix the many to many alias in nested relations. I made a new test in JoinRelationshipUsingAliasTest. I use the same method as the 
The other with the $fullRelationName is an old change but now is a little cleaner. Some times i have relationships that are something like "posts.group.posts" in that case i can't use posts as a key in the callback, because it will be use for posts and posts.group.posts
Checking for posts and latter for posts.group.posts doesnt brake any test, and is only an array and a join extra

Fix nested many to many alias, allow callbacks using the full relation name

---

src/Mixins/RelationshipsExtraMethods.php
tests/JoinRelationshipExtraConditionsTest.php
tests/Models/Comment.php
tests/Models/Post.php
tests/Models/Tag.php
tests/database/factories/TagFactory.php
tests/database/migrations/2020_03_16_000000_create_tables.php

This creates a new method `performJoinForEloquentPowerJoinsForMorphToMany` in `Kirschbaum\PowerJoins\Mixins\RelationshipsExtraMethods` class to correctly handle polymorphic many-to-many relationships.
While the MorphToMany was being handled by the `performJoinForEloquentPowerJoinsForBelongsToMany`, the morph type column query where clause was added to the relation model table join and not the pivot table.
Closes #136

Fix Polymorphic Many-to-Many joins

---

src/PowerJoinClause.php
tests/JoinWithGlobalScopeTest.php
tests/Models/PostWithClosureGlobalScope.php

Adds support for statically added Closure global scopes.
Example:
```php
protected static function boot()
{
parent::boot();
static::addGlobalScope('order', function ($builder) {
$builder->orderBy('first_name')->orderBy('last_name');
});
}
```
This would throw a `Instantiation of 'Closure' is not allowed` before.

feat: support for statically added closure global scopes

---

src/Mixins/JoinRelationship.php
tests/JoinRelationshipTest.php

On a personal project I was trying to change some properties of the pivot as in the README example
```
User::joinRelationship('groups', [
'groups' => [
'groups' => function ($join) {
// ...
},
// group_members is the intermediary table here
'group_members' => fn ($join) => $join->where('group_members.active', true),
]
]);
```
but it was erroring out with the following error (reproduced in the repo).
```
├ Error: Array callback has to contain indices 0 and 1
│ 
│ eloquent-power-joins/src/JoinsHelper.php:88
│ eloquent-power-joins/src/Mixins/JoinRelationship.php:125
│ eloquent-power-joins/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1961
│ eloquent-power-joins/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:23
│ …
```

fix: allow non nested joins to specify pivot information

---

src/Mixins/JoinRelationship.php

Following https://github.com/kirschbaum-development/eloquent-power-joins/issues/172

Upgrading from 3.2.1 to 3.5.0 produces error "Undefined column: 7 ERROR" #172

---

src/Mixins/RelationshipsExtraMethods.php
tests/JoinRelationshipTest.php
tests/Models/Comment.php

In Laravel v11.15 the underlying `HasOneThrough` class changed from `HasManyThrough` to `HasOneOrManyThrough` (in https://github.com/laravel/framework/pull/51851).
Which caused the package to start using `performJoinForEloquentPowerJoinsForBelongsTo` instead of `performJoinForEloquentPowerJoinsForHasManyThrough` causing a `Undefined property: Illuminate\Database\Eloquent\Relations\HasOneThrough::$foreignKey` exception.
This PR adds support back for `HasOneThrough`. I decided to not use the `HasOneOrManyThrough` class directly in the match statement since that class does not exist in older Laravel versions.

Support HasOneThrough

---

src/Mixins/JoinRelationship.php
tests/JoinRelationshipTest.php

Hi there,
I added the ability to join nested MorphTo relations. I wanted to add tests also, but I don't see a matching relation in the database (unless we use `images.imageable` from Post). 
What do you think we should do?

Allow to join nested MorphTo relations

---

src/PowerJoinClause.php
tests/JoinRelationshipTest.php
tests/JoinRelationshipUsingAliasTest.php
tests/OrderByTest.php

When joining a relationship using an alias on a model with soft deletes like:
```
UserProfile::query()->joinRelationshipUsingAlias('user')
```
We get a query thats looks like:
```
SELECT "user_profiles".*
FROM "user_profiles"
INNER JOIN "users" AS "bd9404474a249ec9062d489a4b265c44" 
ON "user_profiles"."user_id" = "bd9404474a249ec9062d489a4b265c44"."id" 
AND "bd9404474a249ec9062d489a4b265c44"."deleted_at" IS NULL
```
So I would expect that when using a named alias like:
```
UserProfile::query()->joinRelationshipUsingAlias('user', 'user_alias')
```
The `deleted_at` conditions for the `User` model would still be used, but instead I'm seeing a query like:
```
SELECT "user_profiles".*
FROM "user_profiles" INNER JOIN "users" AS "user_alias" 
ON "user_profiles"."user_id" = "user_alias"."id"
``` …

fix: include soft delete conditions when using named aliases

---

src/JoinsHelper.php
tests/JoinRelationshipUsingAliasTest.php

Aliases correctly apply on the join part, but not on the soft deletes bit or any subsequent joins.
Please let me know if I've missed something!

Fix alias not fully applying in has one/many through

---

src/JoinsHelper.php
tests/WithCastsPreservationTest.php

Merging casts when cloning

---

src/JoinsHelper.php
src/Mixins/RelationshipsExtraMethods.php
tests/JoinRelationshipUsingAliasTest.php
tests/Models/Like.php
tests/Models/Post.php
tests/Models/User.php
tests/database/migrations/2020_03_16_000000_create_tables.php

In a `hasOneThrough`/`hasManyThrough` relation, it would not apply an alias to the related table.
```php
class Comment # 1: farParent
{
public function postCategory(): HasOneThrough
{
return $this->hasOneThrough(Category::class, Post::class);
}
}
```
Instead, it would look for a potential alias of the 'farParent' but I think this is unintentional. It should look for alias in the 'through' relation (it already did that) and the 'related' relation (it does after this change)
Second fix is for #209 and applies missing alias in soft deletes for `morphOne`/`morphMany`.
PS, i added a new Like model because I need to test soft deletes. I didn't want to add SoftDeletes to another model because it would mean many existing tests needed to be changed.

Fix missing alias in soft deletes in oneThrough / manyThrough / morphOne / morphMany
